import type { AgentAdapter, AstChunk, DefinitionEntry, Manifest } from '../../types.js';

export function buildCopilotAdapter(
  manifest: Manifest,
  chunks: AstChunk[],
  definitions: DefinitionEntry[],
): AgentAdapter {
  return {
    agent: 'copilot',
    format: 'github-copilot-context-v1',
    version: '1',
    generatedAt: new Date().toISOString(),
    sourceRoot: manifest.sourceRoot,
    chunks,
    definitions,
    instructions: [
      'This context pack was generated by ctxpacker-tool for GitHub Copilot.',
      'Use the `chunks` array for inline code context and `definitions` for symbol lookup.',
      `Source root: ${manifest.sourceRoot}`,
      `Generated: ${manifest.createdAt}  |  Expires: ${manifest.expiresAt}`,
    ].join('\n'),
  };
}
